[package]
name = "ch13-realizar"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "inference_engine"
path = "src/inference_engine.rs"

[dependencies]
anyhow.workspace = true

[dev-dependencies]
proptest.workspace = true
