[package]
name = "ch11-decy"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "c_transpilation"
path = "src/c_transpilation.rs"

[dependencies]
anyhow.workspace = true

[dev-dependencies]
proptest.workspace = true
